executable = /home/hep/an1522/dark_tridents_wspace/DM-CNN/sh_files/scorecam_wrapper_128x128.sh

output = logs/scorecam/scorecam_128x128.$(Cluster).$(Process).out
error  = logs/scorecam/scorecam_128x128.$(Cluster).$(Process).err
log    = logs/scorecam/scorecam_128x128.$(Cluster).log

arguments = $(root_file) $(weight_file) $(out_dir) $(entry_number) $(n_pixels) $(tag)

request_gpus = 1
requirements = regexp("V100|A6000", string(TARGET.GPUs_DeviceName))

+MaxRuntime = 84000

queue root_file, weight_file, out_dir, entry_number, n_pixels, tag \
  from /home/hep/an1522/dark_tridents_wspace/outputs/inference/_occlusion_selections/scorecam_tasks.list
